# Site settings
title: ptrsz
author:
  name: Peter Szombathelyi
  email: ptrsz@devnull.com
description: "Things about my interests."
show-downloads: false

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one